version: 2
jobs:
  qa:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile modules
          command: yarn compile
      - run:
          name: Run linters
          command: yarn lint
      - run:
          name: Run tests and calculate code coverage
          command: yarn coverage
      - run:
          name: Publish code coverage report
          command: yarn publish-coverage
  publish-website:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile website
          command: yarn compile --scope=@staticdeploy/website
      - run:
          name: Install staticdeploy cli
          command: |
            yarn global add @staticdeploy/cli
            echo 'export PATH=$PATH:$(yarn global bin)' >> $BASH_ENV
      - run:
          name: Set $BUNDLE_TAG
          command: echo 'export BUNDLE_TAG=${CIRCLE_TAG:-$CIRCLE_BRANCH}' >> $BASH_ENV
      - run:
          name: Create website bundle
          command: |
            staticdeploy create-bundle \
              --from website/build/staticdeploy \
              --name staticdeploy.io \
              --tag $BUNDLE_TAG \
              --description "Commit $CIRCLE_SHA1"
      - run:
          name: Deploy website bundle to staticdeploy.io/_/branchOrTag/
          command: |
            staticdeploy deploy \
              --app staticdeploy.io \
              --entrypoint staticdeploy.io/_/$BUNDLE_TAG/ \
              --bundle staticdeploy.io:$BUNDLE_TAG
      - run:
          name: If on master, also deploy website bundle to staticdeploy.io/
          command: |
            if [ $BUNDLE_TAG = "master" ]; then \
              staticdeploy deploy \
                --app staticdeploy.io \
                --entrypoint staticdeploy.io/ \
                --bundle staticdeploy.io:$BUNDLE_TAG \
            ; fi
  docker-build-push:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies (commands below need lerna)
          command: yarn install --frozen-lockfile
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Set $DOCKER_TAG
          command: echo 'export DOCKER_TAG=${CIRCLE_TAG:-$CIRCLE_BRANCH}' >> $BASH_ENV
      - run:
          name: Build docker image
          command: yarn docker:build
      - run:
          name: Push docker image
          command: yarn docker:push
  npm-publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies (commands below need lerna)
          command: yarn install --frozen-lockfile
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Compile modules
          command: yarn compile
      - run:
          name: Publish npm modules
          command: yarn lerna publish --yes --force-publish=* --skip-git --repo-version ${CIRCLE_TAG#v}

workflows:
  version: 2
  qa-docker-npm:
    jobs:
      - qa:
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - publish-website:
          requires:
            - qa
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - docker-build-push:
          requires:
            - qa
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - npm-publish:
          requires:
            - qa
          # Run only for tags starting with a v, don't run for branches
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
