version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Compile modules
          command: yarn compile
      - run:
          name: Run linters
          command: yarn lint
      - run:
          name: Run tests and calculate code coverage
          command: yarn coverage
      - run:
          name: Publish code coverage report
          command: yarn publish-coverage
  docker-build-push:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies (commands below need lerna)
          command: yarn install
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Set $DOCKER_TAG
          command: echo 'export DOCKER_TAG=${CIRCLE_TAG:-$CIRCLE_BRANCH}' >> $BASH_ENV
      - run:
          name: Build docker image
          command: yarn docker:build
      - run:
          name: Push docker image
          command: yarn docker:push

workflows:
  version: 2
  test-and-docker:
    jobs:
      - test
      - docker-build-push:
          requires:
            - test
